# Generated by Django 5.2 on 2025-04-23 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('power_spectrum', 'Power Spectrum'), ('fourier_transform', 'Fourier Transform'), ('light_curve', 'Light Curve'), ('rebin', 'Rebin'), ('cross_spectrum', 'Cross Spectrum'), ('pds_simulation', 'PDS Simulation'), ('lomb_scargle', 'Lomb-Scargle Periodogram'), ('custom', 'Custom Pipeline')], max_length=50)),
                ('backend', models.CharField(choices=[('stingray', 'Stingray'), ('lightkurve', 'Lightkurve'), ('astropy', 'Astropy')], default='stingray', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Analysis parameters in JSON format')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID for this job', max_length=255, null=True)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_jobs', to='data_app.datafile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('plot', 'Plot'), ('data', 'Data'), ('stats', 'Statistics')], max_length=10)),
                ('file_path', models.FileField(blank=True, help_text='Path to result file if stored as a file', null=True, upload_to='results/')),
                ('content', models.JSONField(blank=True, help_text='Result data if stored as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis_app.analysisjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('analysis_type', models.CharField(choices=[('power_spectrum', 'Power Spectrum'), ('fourier_transform', 'Fourier Transform'), ('light_curve', 'Light Curve'), ('rebin', 'Rebin'), ('cross_spectrum', 'Cross Spectrum'), ('pds_simulation', 'PDS Simulation'), ('lomb_scargle', 'Lomb-Scargle Periodogram'), ('custom', 'Custom Pipeline')], max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'user', 'analysis_type')},
            },
        ),
    ]
