# Generated by Django 5.2 on 2025-04-23 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='datafiles/')),
                ('file_type', models.CharField(choices=[('FITS', 'FITS File'), ('CSV', 'CSV File'), ('TXT', 'Text File'), ('ASCII', 'ASCII File')], max_length=10)),
                ('size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the file')),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
